//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierraSanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string idempresa { get; set; }
        public string idubicacion { get; set; }
        public string idpersoneria { get; set; }
        public string idregimen { get; set; }
        public string idtipo { get; set; }
        public string idmoneda { get; set; }
        public string idcomision { get; set; }
        public string idusuario { get; set; }
        public string control { get; set; }
        public string parametros { get; set; }
        public string ruc { get; set; }
        public string razonsocial { get; set; }
        public string direccion { get; set; }
        public string Abreviatura { get; set; }
        public System.DateTime fechainicio { get; set; }
        public string estado { get; set; }
        public System.DateTime fechacambio { get; set; }
        public string logotipo { get; set; }
        public string fondo { get; set; }
    }
}
