//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierraSanta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesTierraSanta : DbContext
    {
        public EntitiesTierraSanta()
            : base("name=EntitiesTierraSanta")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CuentaContable> CuentaContable { get; set; }
        public virtual DbSet<Cultivo> Cultivo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Fundo> Fundo { get; set; }
        public virtual DbSet<Lote> Lote { get; set; }
        public virtual DbSet<ParametroGenerales> ParametroGenerales { get; set; }
        public virtual DbSet<PlantillaCultivoCabecera> PlantillaCultivoCabecera { get; set; }
        public virtual DbSet<PlantillaCultivoDetalle> PlantillaCultivoDetalle { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TablaActividades> TablaActividades { get; set; }
        public virtual DbSet<TablaCultivos> TablaCultivos { get; set; }
        public virtual DbSet<TablaGenerales> TablaGenerales { get; set; }
        public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }
    }
}
