//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierraSanta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesTierraSanta : DbContext
    {
        public EntitiesTierraSanta()
            : base("name=EntitiesTierraSanta")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CULTIVOS> CULTIVOS { get; set; }
        public virtual DbSet<FINCAS> FINCAS { get; set; }
        public virtual DbSet<LOTES> LOTES { get; set; }
        public virtual DbSet<PLANTILLAS_CULTIVOS> PLANTILLAS_CULTIVOS { get; set; }
        public virtual DbSet<TABLAS_ACTIVIDADES> TABLAS_ACTIVIDADES { get; set; }
        public virtual DbSet<TABLAS_CULTIVOS> TABLAS_CULTIVOS { get; set; }
        public virtual DbSet<EMPRESAS> EMPRESAS { get; set; }
        public virtual DbSet<CUENTAS_CONTABLES> CUENTAS_CONTABLES { get; set; }
        public virtual DbSet<PARAMETROS_GENERALES> PARAMETROS_GENERALES { get; set; }
    }
}
