//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierraSanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETROS_GENERALES
    {
        public string idparametro { get; set; }
        public string idcodigo { get; set; }
        public string idtipo { get; set; }
        public string periodo { get; set; }
        public string idconcepto { get; set; }
        public decimal monto { get; set; }
        public decimal porcentaje { get; set; }
        public decimal cantidad { get; set; }
        public string idusuario { get; set; }
        public string estado { get; set; }
        public System.DateTime fechacambio { get; set; }
        public decimal maximo { get; set; }
        public decimal minimo { get; set; }
    }
}
