//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierraSanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLAS_CULTIVOS
    {
        public string idempresa { get; set; }
        public string idplantilla { get; set; }
        public string idcodigo { get; set; }
        public string idusuario { get; set; }
        public string idactividad { get; set; }
        public decimal cantidad { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public Nullable<System.DateTime> fechacambio { get; set; }
    
        public virtual TABLAS_ACTIVIDADES TABLAS_ACTIVIDADES { get; set; }
        public virtual TABLAS_CULTIVOS TABLAS_CULTIVOS { get; set; }
    }
}
