//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierraSanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones
    {
        public string idubicacion { get; set; }
        public string idusuario { get; set; }
        public string ubicacion { get; set; }
        public string estado { get; set; }
        public System.DateTime fechacambio { get; set; }
    }
}
