//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaContable
    {
        public string idempresa { get; set; }
        public string idcuenta { get; set; }
        public string idusuario { get; set; }
        public string cuenta { get; set; }
        public string cuentaanterior { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public System.DateTime fechacambio { get; set; }
        public string resultado { get; set; }
        public string ctacargo { get; set; }
        public string ctaabono { get; set; }
        public decimal porcentajecargo { get; set; }
        public decimal porcentajeabono { get; set; }
        public string idespecial { get; set; }
        public string idrendicion { get; set; }
        public string iddetalle { get; set; }
        public string idunegocio { get; set; }
        public string idgrupo { get; set; }
    }
}
