//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTS2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Validacion;

    [MetadataType(typeof(UsuarioValidacion))]
    public partial class Usuario
    {
        public System.Guid UsuarioId { get; set; }
        public string Nombre { get; set; }
        public string Login { get; set; }
        public string Clave { get; set; }
        public string Email { get; set; }
        public bool Estado { get; set; }
        public bool EsAdministrador { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    }
}
